[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]
bench = false

[dependencies]
glib = "0.17.9"
glib-sys = "0.17.4"
